name: Executar Scraping e Processamento Real

on:
  schedule:
    - cron: '0 16 17 * *'
  workflow_dispatch:

jobs:
  scrapar-e-processar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Instalar Dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requeriments.txt

    - name: Executar Scraper
      env:
        SCRAPINGBEE_API_KEY: ${{ secrets.SCRAPINGBEE_API_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        python main.py

    - name: Executar Processamento de Dados
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        python processar_dados.py <<< ""
   
    - name: Commitar dados diretamente no repositório
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        

        git add data/processed/*.json
        

        git diff-index --quiet HEAD || git commit -m "bot: atualizando dados extraídos da OLX [skip ci]"
        
        git push
